config/routes.rb
Ising::Application.routes.draw do

  resources :concert_users

  match "/auth/:provider/callback" => "sessions#create"

  match "/ajax/:concertid/comments/" => "comments#add_comment", :via => :post
  match "/ajax/comments/" => "comments#add_comment", :via => :post
  match "/ajax/comments/" => "comments#get_comments", :via => :get

  resources :comments 

  resources :picture_file do
    member do
      post "upload_file"
    end
  end

  resources :concerts

  resources :locals

  resources :group_users

  resources :groups 

  resources :users 

  resources :user_types

  root :to => 'welcome#index'

  resources :type_people
  resources :welcome

  match "/signout" => "sessions#destroy", :as => :signout

  match "public/groups" => "welcome#groups"
  match "public/concerts" => "welcome#concerts"
  match "public/locals" => "welcome#locals"
  match "public/aboutus" => "welcome#aboutus"
  match "public/enter" => "users#register_user"
  match "public/login" => "users#login", :via => :post
  match "public/logout" => "users#logout", :via => :get

  match "/password" => "users#password", :via => :get , :as => :password_root
  match "/password_change" => "users#password_change" , :via => :post , :as => :password_change

  match "/alumno" => "users#alumno", :via => :get , :as => :alumno_root
  match "/alumno_change" => "users#alumno_change" , :via => :post , :as => :alumno_change

  match "/email" => "users#email", :via => :get , :as => :email_root
  match "/email_change" => "users#email_change" , :via => :post , :as => :email_change

  match "/setting" => "users#setting", :via => :get , :as => :setting
  match "/setting_edit" => "users#setting_edit" , :via => :post , :as => :setting_edit

end

app/models/local.rb
class Local < ActiveRecord::Base
  attr_accessible :address, :description, :district, :geolocation, :name, :phone, :pictureref , :estate
  
  validates :name, presence: true, :length => { :minimum => 1, :maximun => 200 }
  validates :address, presence: true, :length => { :minimum => 1, :maximun => 300 }
  validates :phone, presence: true, :length => { :minimum => 6, :maximun => 20 }
  validates :description, presence: true

  acts_as_gmappable :process_geocoding => false

  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    address
  end

end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  layout 'private'
  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locals }
    end
  end

  # GET /locals/1
  # GET /locals/1.json
  def show
    @local = Local.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @local }
    end
  end

  # GET /locals/new
  # GET /locals/new.json
  def new
    @local = Local.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @local }
    end
  end

  # GET /locals/1/edit
  def edit
    @local = Local.find(params[:id])

    @json = Local.all.to_gmaps4rails

  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(params[:local])

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render json: @local, status: :created, location: @local }
      else
        format.html { render action: "new" }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locals/1
  # PUT /locals/1.json
  def update
    @local = Local.find(params[:id])

    respond_to do |format|
      if @local.update_attributes(params[:local])
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local = Local.find(params[:id])
    @local.destroy

    respond_to do |format|
      format.html { redirect_to locals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/locals/_form.html.erb
<%= simple_form_for @local do |f| %>
<div class="input string optional">
  <img id="img" fieldname="local_pictureref" class="ajaxUpload picture_local" src="<%= @local.pictureref ? "/data/#{@local.pictureref}":'#' %>" onerror="this.src='/data/default_local';"/>
  <br/>
  (click en la imagen para cambiar)
</div>
  <%= f.input :pictureref,:as => :hidden, :input_html => {:value => UUID.new.generate } %>
  <%= f.input :name, label: 'Nombre' %>
  <%= f.input :district, label: 'Distrito', collection: 
  [
    'Ancón',
'Ate',
'Barranco',
'Breña',
'Carabayllo',
'Cercado de Lima',
'Chaclacayo',
'Chorrillos',
'Cieneguilla',
'Comas',
'El Agustino',
'Independencia',
'Jesús María',
'La Molina',
'La Victoria',
'Lince',
'Los Olivos',
'Lurigancho-Chosica',
'Lurín',
'Magdalena del Mar',
'Pueblo Libre',
'Miraflores',
'Pachacámac',
'Pucusana',
'Puente Piedra',
'Punta Hermosa',
'Punta Negra',
'Rímac',
'San Bartolo',
'San Borja',
'San Isidro',
'San Juan de Lurigancho',
'San Juan de Miraflores',
'San Luis',
'San Martín de Porres',
'San Miguel',
'Santa Anita',
'Santa María del Mar',
'Santa Rosa',
'Santiago de Surco',
'Surquillo',
'Villa El Salvador',
'Villa María del Triunfo'
  ], include_blank: false %>
  <%= f.input :address, label: 'Direccion' %>
  <%= f.input :phone, label: 'Telefono' %>
  <%= f.input :description, label: 'Descripcion' %>

  <%= gmaps4rails(@json) %>

  <%= f.button :submit , "Registrar" %>
<% end %>

app/views/locals/edit.html.erb
<h1>Mantenimiento de Local</h1>

<%= render 'form' %>

app/views/locals/index.html.erb
<h1>Listado de locales</h1>

<table class="box-table-a">
  <tr>
    <th>Nombre</th>
    <th>Distrito</th>
    <th>Teléfono</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locals.each do |local| %>
  <tr>
    <td>
        <img src="/data/<%= local.pictureref %>" onerror="this.src='/data/default_local';" width="100" />
        <%= local.name %>
        <%= local.name %>
    </td>
    <td><%= local.district %></td>
    <td><%= local.phone %></td>
    <td><%= link_to 'Mostrar', local , class: 'link_button'%></td>
    <td><%= link_to 'Editar', edit_local_path(local) , class: 'link_button' %></td>
    <td><%= link_to 'Borrar', local, method: :delete, data: { confirm: 'Está seguro de borrar?' } , class: 'link_button'%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo local', new_local_path , class: 'link_button' %>

app/views/locals/new.html.erb
<h1>Nuevo local</h1>

<%= render 'form' %>

app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <label>Local:</label> <%= @local.name %>
</div>
<div>
  <img class="picture_local" src="<%= @local.pictureref ? "/data/#{@local.pictureref}":'#'  %>" onerror="this.src='/data/default_local';" />
</div>
<div>
  <label>Decripción:</label><span><%= @local.description %></span><br/>
  <label>Teléfono:</label><span><%= @local.phone %></span><br/>
  <label>Dirección:</label><span><%= @local.address %> - <%= @local.district %></span><br/>
  <label>Google Map:</label><span><%= @local.geolocation %></span><br/>
</div>
<div>
<%= link_to 'Editar', edit_local_path(@local) , class: 'link_button'%> 
<%= link_to 'Regresar', locals_path, class: 'link_button' %>
</div>