config/routes.rb
Ising::Application.routes.draw do

  resources :concert_users

  match "/auth/:provider/callback" => "sessions#create"

  match "/ajax/:concertid/comments/" => "comments#add_comment", :via => :post
  match "/ajax/comments/" => "comments#add_comment", :via => :post
  match "/ajax/comments/" => "comments#get_comments", :via => :get

  resources :comments 

  resources :picture_file do
    member do
      post "upload_file"
    end
  end

  resources :concerts

  resources :locals

  resources :group_users

  resources :groups 

  resources :users 

  resources :user_types

  root :to => 'welcome#index'

  resources :type_people
  resources :welcome

  match "/signout" => "sessions#destroy", :as => :signout

  match "public/groups" => "welcome#groups"
  match "public/concerts" => "welcome#concerts"
  match "public/locals" => "welcome#locals"
  match "public/aboutus" => "welcome#aboutus"
  match "public/enter" => "users#register_user"
  match "public/login" => "users#login", :via => :post
  match "public/logout" => "users#logout", :via => :get

  match "/password" => "users#password", :via => :get , :as => :password_root
  match "/password_change" => "users#password_change" , :via => :post , :as => :password_change

  match "/alumno" => "users#alumno", :via => :get , :as => :alumno_root
  match "/alumno_change" => "users#alumno_change" , :via => :post , :as => :alumno_change

  match "/email" => "users#email", :via => :get , :as => :email_root
  match "/email_change" => "users#email_change" , :via => :post , :as => :email_change

  match "/setting" => "users#setting", :via => :get , :as => :setting
  match "/setting_edit" => "users#setting_edit" , :via => :post , :as => :setting_edit

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :users, :group_users, :biography, :genre, :name, :picture, :user_ids, :pictureref, :selected_users_id

  has_many :group_users
  has_many :users, :through => :group_users

  attr_accessor :selected_users_id # attributo virtual no en base de datos

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout 'private'
  # GET /groups
  # GET /groups.json
  def index
    if current_user.user_type.isadmin
      @groups = Group.all
    else
      @groups = Group.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  def add_users
    @group = Group.find(params[:id])
    user_type_id =  UserType.select("id").where(:name => 'Alumno').first.id
    @users = User.where(:user_type_id => user_type_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    #where(:user_type_id => 2).
    @users = User.all()

    
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    # initialize array (it is not saved in db)
    @group.selected_users_id=[]

    @group.users.each do |cur|
      @group.selected_users_id << cur.id
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        # add users to relationship
        @group.selected_users_id.each do |user_id|
          if not user_id.blank?
            groupUser = GroupUser.new(:group_id => @group.id,:user_id => user_id)
            groupUser.save
          end
        end

        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    @group.selected_users_id = Group.new(params[:group]).selected_users_id
    Rails.logger.info "====================9 #{@group.selected_users_id}"

    respond_to do |format|
      if @group.update_attributes(params[:group])
        # delete all relation
        @group.group_users.delete_all
        # add new relations again
        @group.selected_users_id.each do |user_id|
          if not user_id.blank?
            groupUser = GroupUser.new(:group_id => @group.id,:user_id => user_id)
            groupUser.save
          end
        end

        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
<% if f.error_notification %>
<% @group.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
<% end %>

<%= f.input :pictureref,:as => :hidden, :input_html => {:value => UUID.new.generate } %>
<div class="input string optional">
  <img id="img" fieldname="group_pictureref" class="ajaxUpload picture_group" src="<%= @group.pictureref ? "/data/#{@group.pictureref}":'#' %>" onerror="this.src='/data/default_group';" />
  <br/>
  (click en la imagen para cambiar)
</div>

<%= f.input :name, label: 'Nombre', html:{class:'form_field'} %>
<%= f.input :genre, label: 'Genero Musical', collection: 
[
'Balada',
'Ballenato',
'Pop',
'Rock',
'Salsa',
'Tropical',
'Popular',
'Ranchera',
'Techno',
'Regge',
'Reggeton',
'Musica clasica',
'Latina',
'Electonica',
'Jazz',
'Infantil',
'Rap',
'Tango ',
'Ska',
'Flamenco'
], include_blank: false   %>
<%= f.input :biography, label: 'Biograf&iacute;a'%>

<%= f.input :selected_users_id, :collection => User.all, :label_method => lambda { 
|r| "<img width='30' onerror='this.src=\"/data/default_user\";' src='/data/#{r.pictureref}' /> #{r.lastname1} #{r.lastname2}, #{r.givenname}".html_safe } , :value_method => :id, :as => :check_boxes,:item_wrapper_class => 'checkbox_container', label: "Miembros" %>

<%= f.button :submit %>


<% end %>

app/views/groups/edit.html.erb
<h1>Edición de grupo</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @group, class: 'link_button' %> |
<%= link_to 'Regresar', groups_path, class: 'link_button' %>

app/views/groups/index.html.erb
<h1>Listado de grupos</h1>

<table class="box-table-a">
  <tr>
    <th>Grupo</th>
    <th>Genero Musical</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @groups.each do |group| %>
  <tr>
    <td>
      <img src="/data/<%= group.pictureref %>" onerror="this.src='/data/default_group';" width="100" />
      <br/>
      <label><%= group.name %></label> 
      <br/>
      Miembros:
      <br/>
      <% group.users.each do |cur_user|%>
        <img class="picture_user small"  src="<%= cur_user.pictureref ? "/data/#{cur_user.pictureref}":'#'  %>" onerror="this.src='/data/default_user';" />
        <span><%= cur_user.lastname1 %> <%= cur_user.lastname2 %>, <%= cur_user.givenname %></span><br/>
      <% end %>
    </td>
    <td><%= group.genre %></td>
    <td><%= link_to 'Mostrar', group, class: 'link_button' %></td>
    <td><%= link_to 'Editar', edit_group_path(group), class: 'link_button' %></td>
    <td><%= link_to 'Borrar', group, method: :delete, data: { confirm: 'Está seguro de borrar?' } , class: 'link_button'%></td>
  </tr>
  <% end %>
</table>

<br />

<%= link_to 'Nuevo grupo', new_group_path, class: 'link_button' %>

app/views/groups/new.html.erb
<h1>Nuevo grupo</h1>

<%= render 'form' %>

<%= link_to 'Regresar', groups_path , class: 'link_button' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <label>Grupo:</label> <%= @group.name %>
</div>
<div>
  <img class="picture_local" src="<%= @group.pictureref ? "/data/#{@group.pictureref}":'#'  %>" onerror="this.src='/data/default_group';" />
</div>
<div>
  <label>Género:</label><span><%= @group.genre %></span><br/>
  <label>Biografía:</label><span><%= @group.biography %></span><br/>
</div>
<div>
  <ul>
  <% @group.users.each do |cur_user|%>
    <li>
      <img class="picture_user small"  src="<%= cur_user.pictureref ? "/data/#{cur_user.pictureref}":'#'  %>" onerror="this.src='/data/default_user';" />
      <span><%= cur_user.lastname1 %> <%= cur_user.lastname2 %>, <%= cur_user.givenname %></span>
    </li>
  <% end %>
</ul>
</div>
<div>
<%= link_to 'Editar', edit_group_path(@group) , class: 'link_button'%> |
<%= link_to 'Regresar', groups_path , class: 'link_button'%>
</div>