config/routes.rb
Ising::Application.routes.draw do

  resources :concert_users

  match "/auth/:provider/callback" => "sessions#create"

  match "/ajax/:concertid/comments/" => "comments#add_comment", :via => :post
  match "/ajax/comments/" => "comments#add_comment", :via => :post
  match "/ajax/comments/" => "comments#get_comments", :via => :get

  resources :comments 

  resources :picture_file do
    member do
      post "upload_file"
    end
  end

  resources :concerts

  resources :locals

  resources :group_users

  resources :groups 

  resources :users 

  resources :user_types

  root :to => 'welcome#index'

  resources :type_people
  resources :welcome

  match "/signout" => "sessions#destroy", :as => :signout

  match "public/groups" => "welcome#groups"
  match "public/concerts" => "welcome#concerts"
  match "public/locals" => "welcome#locals"
  match "public/aboutus" => "welcome#aboutus"
  match "public/enter" => "users#register_user"
  match "public/login" => "users#login", :via => :post
  match "public/logout" => "users#logout", :via => :get

  match "/password" => "users#password", :via => :get , :as => :password_root
  match "/password_change" => "users#password_change" , :via => :post , :as => :password_change

  match "/alumno" => "users#alumno", :via => :get , :as => :alumno_root
  match "/alumno_change" => "users#alumno_change" , :via => :post , :as => :alumno_change

  match "/email" => "users#email", :via => :get , :as => :email_root
  match "/email_change" => "users#email_change" , :via => :post , :as => :email_change

  match "/setting" => "users#setting", :via => :get , :as => :setting
  match "/setting_edit" => "users#setting_edit" , :via => :post , :as => :setting_edit

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  belongs_to :local
  belongs_to :group

  has_many :concert_users
  has_many :user , :through => :concert_users


  attr_accessible :dateend, :datestart, :description, :headline, :totalscore , :local_id , :group_id  , :estate
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  layout 'private'
  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concerts }
    end
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
    @concert = Concert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concert }
    end
  end

  # GET /concerts/new
  # GET /concerts/new.json
  def new
    @concert = Concert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concert }
    end
  end

  # GET /concerts/1/edit
  def edit
    @concert = Concert.find(params[:id])
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(params[:concert])

    respond_to do |format|
      if @concert.save

        @concert.update_attribute('estate','ACT')
        @local = Local.find(@concert.local.id)
        @local.update_attribute('estate','ACT')

        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render json: @concert, status: :created, location: @concert }
      else
        format.html { render action: "new" }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /concerts/1
  # PUT /concerts/1.json
  def update
    @concert = Concert.find(params[:id])

    respond_to do |format|
      if @concert.update_attributes(params[:concert])
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy

    @concerts = Concert.find(params[:id])
    @concerts.update_attribute('estate','INA')

    respond_to do |format|
      format.html { redirect_to concerts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_form.html.erb
<%= simple_form_for @concert do |f| %>
<% if f.error_notification %>
<% @concert.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
<% end %>

<%= f.input :headline, label: 'Nombre' %>
<%= f.input :description, label: 'Descripción' %>
<%= f.input :datestart, label: 'Fecha de Inicio' %>
<%= f.input :dateend, label: 'Fecha de Fin' %>
<%= f.input :totalscore, label: 'Calificación', :collection => 1..5, :as => :radio %>
<%= f.input :local_id, label: 'Local', :collection => Local.all %>
<%= f.input :group_id, label: 'Grupo', :collection => Group.all %>
<%= f.input :estate, :as => 'hidden',  html:{value:'ACT'} %>
<%= f.button :submit, label: 'Crear concierto' %>

<% end %>

app/views/concerts/edit.html.erb
<h1>Edición de concierto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @concert , class: 'link_button'%> |
<%= link_to 'Regresar', concerts_path , class: 'link_button'%>

app/views/concerts/index.html.erb
<h1>Listado de conciertos</h1>

<table class="box-table-a">
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Fecha inicio</th>
    <th>Fecha final</th>
    <th>Calificación</th>
    <th>Local</th>
    <th>Grupo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @concerts.each do |concert| %>
  <tr>
    <td><%= concert.headline %></td>
    <td><%= concert.description %></td>
    <td><%= concert.datestart %></td>
    <td><%= concert.dateend %></td>
    <td><%= concert.totalscore %></td>
    <td><%= concert.local.name %></td>
    <td><%= concert.group.name %></td>
    <td><%= link_to 'Mostrar', concert , class: 'link_button'%></td>
    <td><%= link_to 'Editar', edit_concert_path(concert) , class: 'link_button'%></td>
    <td><%= link_to 'Borrar', concert, method: :delete, data: { confirm: 'Está seguro de borrar?' } , class: 'link_button'%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo concierto', new_concert_path , class: 'link_button'%>

app/views/concerts/new.html.erb
<h1>Nuevo concierto</h1>

<%= render 'form' %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @concert.headline %>
</p>

<p>
  <b>Descripción:</b>
  <%= @concert.description %>
</p>

<p>
  <b>Fecha de Inicio:</b>
  <%= @concert.datestart %>
</p>

<p>
  <b>Fecha Fin:</b>
  <%= @concert.dateend %>
</p>

<p>
  <b>Calificación:</b>
  <%= @concert.totalscore %>
</p>

<p>
  <b>Local:</b>
  <%= @concert.local.name %>
</p>

<p>
  <b>Grupo:</b>
  <%= @concert.group.name %>
</p>

<p>
  <b>Estado:</b>
  <%= @concert.estate %>
</p>

<%= link_to 'Editar', edit_concert_path(@concert) , class: 'link_button'%> |
<%= link_to 'Regresar', concerts_path , class: 'link_button'%>